version: 2
appName: Checkout Create Order Pipeline
basePackage: org.pipelineframework.checkout.createorder
transport: GRPC
messages:
  OrderRequest:
    fields:
      - number: 1
        name: requestId
        type: uuid
      - number: 2
        name: customerId
        type: uuid
      - number: 3
        name: items
        type: string
  OrderLineItem:
    fields:
      - number: 1
        name: requestId
        type: uuid
      - number: 2
        name: customerId
        type: uuid
      - number: 3
        name: sku
        type: string
      - number: 4
        name: quantity
        type: int32
  InitialOrder:
    fields:
      - number: 1
        name: orderId
        type: uuid
      - number: 2
        name: customerId
        type: uuid
      - number: 3
        name: itemCount
        type: int32
  ReadyOrder:
    fields:
      - number: 1
        name: orderId
        type: uuid
      - number: 2
        name: customerId
        type: uuid
      - number: 3
        name: readyAt
        type: timestamp
steps:
  - name: Order Request Process
    cardinality: ONE_TO_MANY
    inputTypeName: OrderRequest
    outputTypeName: OrderLineItem
  - name: Order Create
    cardinality: MANY_TO_ONE
    inputTypeName: OrderLineItem
    outputTypeName: InitialOrder
  - name: Order Ready
    cardinality: ONE_TO_ONE
    inputTypeName: InitialOrder
    outputTypeName: ReadyOrder
