version: 2
appName: Checkout Create Order Pipeline
basePackage: org.pipelineframework.checkout.createorder
transport: GRPC
types:
  OrderRequest:
    fields:
      - [1, requestId, uuid]
      - [2, customerId, uuid]
      - number: 3
        name: items
        type: OrderLineItem
        repeated: true
  OrderLineItem:
    fields:
      - [1, requestId, uuid]
      - [2, customerId, uuid]
      - [3, sku, string]
      - [4, quantity, int32]
  InitialOrder:
    fields:
      - [1, orderId, uuid]
      - [2, requestId, uuid]
      - [3, customerId, uuid]
      - [4, itemCount, int32]
  ReadyOrder:
    fields:
      - [1, orderId, uuid]
      - [2, requestId, uuid]
      - [3, customerId, uuid]
      - [4, readyAt, timestamp]
contract:
  input: OrderRequest
  output: ReadyOrder
steps:
  - name: Order Request Process
    cardinality: ONE_TO_MANY
    output: OrderLineItem
  - name: Order Create
    cardinality: MANY_TO_ONE
    output: InitialOrder
  - name: Order Ready
    cardinality: ONE_TO_ONE
    output: ReadyOrder
