appName: "FTGo Checkout Pipeline"
basePackage: "org.pipelineframework.checkout.ftgo.checkout"
transport: "GRPC"
steps:
  - name: "Checkout Validate Request"
    cardinality: "ONE_TO_ONE"
    inputTypeName: "PlaceOrderRequest"
    inputFields:
      - name: "requestId"
        type: "UUID"
        protoType: "string"
      - name: "customerId"
        type: "UUID"
        protoType: "string"
      - name: "restaurantId"
        type: "UUID"
        protoType: "string"
      - name: "items"
        type: "String"
        protoType: "string"
      - name: "totalAmount"
        type: "BigDecimal"
        protoType: "string"
      - name: "currency"
        type: "String"
        protoType: "string"
    outputTypeName: "ValidatedOrderRequest"
    outputFields:
      - name: "requestId"
        type: "UUID"
        protoType: "string"
      - name: "customerId"
        type: "UUID"
        protoType: "string"
      - name: "restaurantId"
        type: "UUID"
        protoType: "string"
      - name: "items"
        type: "String"
        protoType: "string"
      - name: "totalAmount"
        type: "BigDecimal"
        protoType: "string"
      - name: "currency"
        type: "String"
        protoType: "string"
      - name: "validatedAt"
        type: "Instant"
        protoType: "string"
  - name: "Checkout Create Pending"
    cardinality: "ONE_TO_ONE"
    inputTypeName: "ValidatedOrderRequest"
    inputFields:
      - name: "requestId"
        type: "UUID"
        protoType: "string"
      - name: "customerId"
        type: "UUID"
        protoType: "string"
      - name: "restaurantId"
        type: "UUID"
        protoType: "string"
      - name: "items"
        type: "String"
        protoType: "string"
      - name: "totalAmount"
        type: "BigDecimal"
        protoType: "string"
      - name: "currency"
        type: "String"
        protoType: "string"
      - name: "validatedAt"
        type: "Instant"
        protoType: "string"
    outputTypeName: "OrderPending"
    outputFields:
      - name: "orderId"
        type: "UUID"
        protoType: "string"
      - name: "requestId"
        type: "UUID"
        protoType: "string"
      - name: "customerId"
        type: "UUID"
        protoType: "string"
      - name: "restaurantId"
        type: "UUID"
        protoType: "string"
      - name: "totalAmount"
        type: "BigDecimal"
        protoType: "string"
      - name: "currency"
        type: "String"
        protoType: "string"
      - name: "createdAt"
        type: "Instant"
        protoType: "string"
