appName: "FTGo Consumer Validation Pipeline"
basePackage: "org.pipelineframework.checkout.ftgo.consumer"
transport: "GRPC"
steps:
  - name: "Consumer Validate Order"
    cardinality: "ONE_TO_ONE"
    inputTypeName: "OrderPending"
    inputFields:
      - name: "orderId"
        type: "UUID"
        protoType: "string"
      - name: "requestId"
        type: "UUID"
        protoType: "string"
      - name: "customerId"
        type: "UUID"
        protoType: "string"
      - name: "restaurantId"
        type: "UUID"
        protoType: "string"
      - name: "totalAmount"
        type: "BigDecimal"
        protoType: "string"
      - name: "currency"
        type: "String"
        protoType: "string"
      - name: "createdAt"
        type: "Instant"
        protoType: "string"
    outputTypeName: "OrderApproved"
    outputFields:
      - name: "orderId"
        type: "UUID"
        protoType: "string"
      - name: "requestId"
        type: "UUID"
        protoType: "string"
      - name: "customerId"
        type: "UUID"
        protoType: "string"
      - name: "restaurantId"
        type: "UUID"
        protoType: "string"
      - name: "totalAmount"
        type: "BigDecimal"
        protoType: "string"
      - name: "currency"
        type: "String"
        protoType: "string"
      - name: "approvedAt"
        type: "Instant"
        protoType: "string"
      - name: "riskBand"
        type: "String"
        protoType: "string"
