appName: "FTGo Payment Capture Pipeline"
basePackage: "org.pipelineframework.checkout.ftgo.payment"
transport: "GRPC"
steps:
  - name: "Payment Capture"
    cardinality: "ONE_TO_ONE"
    inputTypeName: "OrderDelivered"
    inputFields:
      - name: "orderId"
        type: "UUID"
        protoType: "string"
      - name: "customerId"
        type: "UUID"
        protoType: "string"
      - name: "dispatchId"
        type: "UUID"
        protoType: "string"
      - name: "courierId"
        type: "UUID"
        protoType: "string"
      - name: "deliveredAt"
        type: "Instant"
        protoType: "string"
    outputTypeName: "PaymentCaptured"
    outputFields:
      - name: "orderId"
        type: "UUID"
        protoType: "string"
      - name: "paymentId"
        type: "UUID"
        protoType: "string"
      - name: "capturedAt"
        type: "Instant"
        protoType: "string"
      - name: "amount"
        type: "BigDecimal"
        protoType: "string"
      - name: "currency"
        type: "String"
        protoType: "string"
