version: 1
layout: modular
validation: auto

defaults:
  runtime: local
  module: per-step
  synthetic:
    module: plugin

runtimes:
  local: {}

modules:
  input-csv-file-processing-svc:
    runtime: local
  payments-processing-svc:
    runtime: local
  payment-status-svc:
    runtime: local
  persistence-svc:
    runtime: local
  orchestrator-svc:
    runtime: local

steps:
  process-csv-payments-input:
    module: input-csv-file-processing-svc
  await-payment-provider:
    module: orchestrator-svc
  process-approved-payment-status:
    module: payment-status-svc
  process-unapproved-payment-status:
    module: payment-status-svc
  finalize-payment-output:
    module: payment-status-svc
