appName: "Checkout Deliver Order Pipeline"
basePackage: "org.pipelineframework.checkout.deliverorder"
transport: "GRPC"
steps:
  - name: "Order Dispatch"
    cardinality: "ONE_TO_ONE"
    inputTypeName: "ReadyOrder"
    inputFields:
      - name: "orderId"
        type: "UUID"
        protoType: "string"
      - name: "customerId"
        type: "UUID"
        protoType: "string"
      - name: "readyAt"
        type: "Instant"
        protoType: "string"
    outputTypeName: "DispatchedOrder"
    outputFields:
      - name: "orderId"
        type: "UUID"
        protoType: "string"
      - name: "customerId"
        type: "UUID"
        protoType: "string"
      - name: "readyAt"
        type: "Instant"
        protoType: "string"
      - name: "dispatchId"
        type: "UUID"
        protoType: "string"
      - name: "dispatchedAt"
        type: "Instant"
        protoType: "string"
  - name: "Order Delivered"
    cardinality: "ONE_TO_ONE"
    inputTypeName: "DispatchedOrder"
    inputFields:
      - name: "orderId"
        type: "UUID"
        protoType: "string"
      - name: "customerId"
        type: "UUID"
        protoType: "string"
      - name: "readyAt"
        type: "Instant"
        protoType: "string"
      - name: "dispatchId"
        type: "UUID"
        protoType: "string"
      - name: "dispatchedAt"
        type: "Instant"
        protoType: "string"
    outputTypeName: "DeliveredOrder"
    outputFields:
      - name: "orderId"
        type: "UUID"
        protoType: "string"
      - name: "customerId"
        type: "UUID"
        protoType: "string"
      - name: "readyAt"
        type: "Instant"
        protoType: "string"
      - name: "dispatchId"
        type: "UUID"
        protoType: "string"
      - name: "dispatchedAt"
        type: "Instant"
        protoType: "string"
      - name: "deliveredAt"
        type: "Instant"
        protoType: "string"
