version: 2
appName: csv-payments
basePackage: org.pipelineframework.csv
transport: GRPC
aspects:
  persistence:
    enabled: true
    scope: GLOBAL
    position: AFTER_STEP
    config:
      pluginImplementationClass: org.pipelineframework.plugin.persistence.PersistenceService
      enabledTargets:
        - GRPC_SERVICE
        - CLIENT_STEP
messages:
  CsvFolder:
    fields:
      - number: 1
        name: path
        type: path
  CsvPaymentsInputFile:
    fields:
      - number: 1
        name: id
        type: uuid
      - number: 2
        name: filepath
        type: path
      - number: 3
        name: csvFolderPath
        type: path
  PaymentRecord:
    fields:
      - number: 1
        name: id
        type: uuid
      - number: 2
        name: csvId
        type: string
      - number: 3
        name: recipient
        type: string
      - number: 4
        name: amount
        type: decimal
      - number: 5
        name: currency
        type: currency
      - number: 6
        name: csvPaymentsInputFilePath
        type: path
  AckPaymentSent:
    fields:
      - number: 1
        name: id
        type: uuid
      - number: 2
        name: conversationId
        type: uuid
      - number: 3
        name: status
        type: int64
      - number: 4
        name: message
        type: string
      - number: 5
        name: paymentRecordId
        type: uuid
      - number: 6
        name: paymentRecord
        type: PaymentRecord
  PaymentStatus:
    fields:
      - number: 1
        name: id
        type: uuid
      - number: 2
        name: reference
        type: string
      - number: 3
        name: status
        type: string
      - number: 4
        name: message
        type: string
      - number: 5
        name: fee
        type: decimal
      - number: 6
        name: ackPaymentSentId
        type: uuid
      - number: 7
        name: ackPaymentSent
        type: AckPaymentSent
  PaymentOutput:
    fields:
      - number: 1
        name: id
        type: uuid
      - number: 2
        name: csvPaymentsOutputFilename
        type: string
      - number: 3
        name: csvId
        type: string
      - number: 4
        name: recipient
        type: string
      - number: 5
        name: amount
        type: decimal
      - number: 6
        name: currency
        type: currency
      - number: 7
        name: conversationId
        type: uuid
      - number: 8
        name: status
        type: int64
      - number: 9
        name: message
        type: string
      - number: 10
        name: fee
        type: decimal
      - number: 11
        name: paymentStatus
        type: PaymentStatus
  CsvPaymentsOutputFile:
    fields:
      - number: 1
        name: id
        type: uuid
      - number: 2
        name: filepath
        type: path
      - number: 3
        name: csvFolderPath
        type: path
steps:
  - name: Process Folder
    service: org.pipelineframework.csv.service.ProcessFolderService
    cardinality: EXPANSION
    input: org.pipelineframework.csv.common.domain.CsvFolder
    inputTypeName: CsvFolder
    inboundMapper: org.pipelineframework.csv.common.mapper.CsvFolderMapper
    output: org.pipelineframework.csv.common.domain.CsvPaymentsInputFile
    outputTypeName: CsvPaymentsInputFile
    outboundMapper: org.pipelineframework.csv.common.mapper.CsvPaymentsInputFileMapper
  - name: Process Csv Payments Input
    service: org.pipelineframework.csv.service.ProcessCsvPaymentsInputService
    cardinality: EXPANSION
    input: org.pipelineframework.csv.common.domain.CsvPaymentsInputFile
    inputTypeName: CsvPaymentsInputFile
    inboundMapper: org.pipelineframework.csv.common.mapper.CsvPaymentsInputFileMapper
    output: org.pipelineframework.csv.common.domain.PaymentRecord
    outputTypeName: PaymentRecord
    outboundMapper: org.pipelineframework.csv.common.mapper.PaymentRecordMapper
  - name: Process Send Payment Record
    service: org.pipelineframework.csv.service.ProcessSendPaymentRecordService
    cardinality: ONE_TO_ONE
    input: org.pipelineframework.csv.common.domain.PaymentRecord
    inputTypeName: PaymentRecord
    inboundMapper: org.pipelineframework.csv.common.mapper.PaymentRecordMapper
    output: org.pipelineframework.csv.common.domain.AckPaymentSent
    outputTypeName: AckPaymentSent
    outboundMapper: org.pipelineframework.csv.common.mapper.AckPaymentSentMapper
  - name: Process Ack Payment Sent
    service: org.pipelineframework.csv.service.ProcessAckPaymentSentService
    cardinality: ONE_TO_ONE
    input: org.pipelineframework.csv.common.domain.AckPaymentSent
    inputTypeName: AckPaymentSent
    inboundMapper: org.pipelineframework.csv.common.mapper.AckPaymentSentMapper
    output: org.pipelineframework.csv.common.domain.PaymentStatus
    outputTypeName: PaymentStatus
    outboundMapper: org.pipelineframework.csv.common.mapper.PaymentStatusMapper
  - name: Process Payment Status
    service: org.pipelineframework.csv.service.ProcessPaymentStatusService
    cardinality: ONE_TO_ONE
    input: org.pipelineframework.csv.common.domain.PaymentStatus
    inputTypeName: PaymentStatus
    inboundMapper: org.pipelineframework.csv.common.mapper.PaymentStatusMapper
    output: org.pipelineframework.csv.common.domain.PaymentOutput
    outputTypeName: PaymentOutput
    outboundMapper: org.pipelineframework.csv.common.mapper.PaymentOutputMapper
  - name: Process Csv Payments Output File
    service: org.pipelineframework.csv.service.ProcessCsvPaymentsOutputFileService
    cardinality: MANY_TO_MANY
    input: org.pipelineframework.csv.common.domain.PaymentOutput
    inputTypeName: PaymentOutput
    inboundMapper: org.pipelineframework.csv.common.mapper.PaymentOutputMapper
    output: org.pipelineframework.csv.common.domain.CsvPaymentsOutputFile
    outputTypeName: CsvPaymentsOutputFile
    outboundMapper: org.pipelineframework.csv.common.mapper.CsvPaymentsOutputFileMapper
