pipeline.orchestrator.mode=QUEUE_ASYNC
pipeline.orchestrator.idempotency-policy=CLIENT_KEY_REQUIRED
quarkus.grpc.clients.process-payment-capture-order.host=127.0.0.1
quarkus.grpc.clients.process-payment-capture-order.port=9000
quarkus.grpc.clients.process-payment-capture-order.plain-text=true
