pipeline.orchestrator.mode=QUEUE_ASYNC
pipeline.orchestrator.idempotency-policy=CLIENT_KEY_REQUIRED
quarkus.grpc.clients.process-restaurant-accept-order.host=127.0.0.1
quarkus.grpc.clients.process-restaurant-accept-order.port=9000
quarkus.grpc.clients.process-restaurant-accept-order.plain-text=true
