<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.pipelineframework</groupId>
        <artifactId>pipeline-framework-root</artifactId>
        <version>26.9.1</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>pipeline-segments</artifactId>
    <packaging>pom</packaging>
    <name>Pipeline Segments</name>
    <properties>
        <pdfbox.version>3.0.7</pdfbox.version>
        <poi.version>5.5.1</poi.version>
    </properties>
    <modules>
        <module>document-text-extraction</module>
    </modules>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.apache.pdfbox</groupId>
                <artifactId>pdfbox</artifactId>
                <version>${pdfbox.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.poi</groupId>
                <artifactId>poi-ooxml</artifactId>
                <version>${poi.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
